In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("38-concrete_data.csv")

In [3]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1030 non-null   float64
 1   Blast Furnace Slag  1030 non-null   float64
 2   Fly Ash             1030 non-null   float64
 3   Water               1030 non-null   float64
 4   Superplasticizer    1030 non-null   float64
 5   Coarse Aggregate    1030 non-null   float64
 6   Fine Aggregate      1030 non-null   float64
 7   Age                 1030 non-null   int64
 8   Strength            1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [5]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
df.duplicated().sum()

25

In [8]:
df[df.duplicated()]

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
77,425.0,106.3,0.0,153.5,16.5,852.1,887.1,3,33.40
80,425.0,106.3,0.0,153.5,16.5,852.1,887.1,3,33.40
86,362.6,189.0,0.0,164.9,11.6,944.7,755.8,3,35.30
88,362.6,189.0,0.0,164.9,11.6,944.7,755.8,3,35.30
91,362.6,189.0,0.0,164.9,11.6,944.7,755.8,3,35.30
100,425.0,106.3,0.0,153.5,16.5,852.1,887.1,7,49.20
103,425.0,106.3,0.0,153.5,16.5,852.1,887.1,7,49.20
109,362.6,189.0,0.0,164.9,11.6,944.7,755.8,7,55.90
111,362.6,189.0,0.0,164.9,11.6,944.7,755.8,7,55.90
123,425.0,106.3,0.0,153.5,16.5,852.1,887.1,28,60.29
126,425.0,106.3,0.0,153.5,16.5,852.1,887.1,28,60.29
132,362.6,189.0,0.0,164.9,11.6,944.7,755.8,28,71.30
134,362.6,189.0,0.0,164.9,11.6,944.7,755.8,28,71.30
137,362.6,189.0,0.0,164.9,11.6,944.7,755.8,28,71.30
146,425.0,106.3,0.0,153.5,16.5,852.1,887.1,56,64.30
149,425.0,106.3,0.0,153.5,16.5,852.1,887.1,56,64.30
155,362.6,189.0,0.0,164.9,11.6,944.7,755.8,56,77.30
157,362.6,189.0,0.0,164.9,11.6,944.7,755.8,56,77.30
160,362.6,189.0,0.0,164.9,11.6,944.7,755.8,56,77.30
169,425.0,106.3,0.0,153.5,16.5,852.1,887.1,91,65.20
172,425.0,106.3,0.0,153.5,16.5,852.1,887.1,91,65.20
177,362.6,189.0,0.0,164.9,11.6,944.7,755.8,91,79.30
179,362.6,189.0,0.0,164.9,11.6,944.7,755.8,91,79.30
182,362.6,189.0,0.0,164.9,11.6,944.7,755.8,91,79.30
809,252.0,0.0,0.0,185.0,0.0,1111.0,784.0,28,19.69

In [9]:
df.drop_duplicates(ignore_index=True,inplace=True)

In [10]:
df.duplicated().sum()

0

In [11]:
df.shape

(1005, 9)

In [16]:
df.corr()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
Cement,1.000000,-0.303324,-0.385610,-0.056625,0.060906,-0.086205,-0.245375,0.086348,0.488283
Blast Furnace Slag,-0.303324,1.000000,-0.312352,0.130262,0.019800,-0.277559,-0.289685,-0.042759,0.103374
Fly Ash,-0.385610,-0.312352,1.000000,-0.283314,0.414213,-0.026468,0.090262,-0.158940,-0.080648
Water,-0.056625,0.130262,-0.283314,1.000000,-0.646946,-0.212480,-0.444915,0.279284,-0.269624
Superplasticizer,0.060906,0.019800,0.414213,-0.646946,1.000000,-0.241721,0.207993,-0.194076,0.344209
Coarse Aggregate,-0.086205,-0.277559,-0.026468,-0.212480,-0.241721,1.000000,-0.162187,-0.005264,-0.144717
Fine Aggregate,-0.245375,-0.289685,0.090262,-0.444915,0.207993,-0.162187,1.000000,-0.156572,-0.186448
Age,0.086348,-0.042759,-0.158940,0.279284,-0.194076,-0.005264,-0.156572,1.000000,0.337367
Strength,0.488283,0.103374,-0.080648,-0.269624,0.344209,-0.144717,-0.186448,0.337367,1.000000

# Maneul Olarak Gradient Boosting

- Bu gerçek değil aslında tüm parametrelerle oynamıyoruz sadece birini değiştiriyoruz ama buradaki asıl amaç mantık nasıl oluyor bunu kavramak.

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = df.drop('Strength', axis=1)
y = df.Strength

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=36)

In [17]:
from sklearn.tree import DecisionTreeRegressor

In [18]:
# first weark learner
tree_reg1 = DecisionTreeRegressor(max_depth=3)
tree_reg1.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=3)

In [19]:
# residual error
y2 = y_train - tree_reg1.predict(X_train)
y2[:5]

886   -11.258000
249     6.131730
534     4.604016
566    -4.825984
852    -8.288270
Name: Strength, dtype: float64

In [20]:
# second weak learner
tree_reg2 = DecisionTreeRegressor(max_depth=4)
tree_reg2.fit(X_train, y2)

DecisionTreeRegressor(max_depth=4)

In [23]:
y3 = y2 - tree_reg2.predict(X_train)
y3[:5]

886    0.525776
249    0.493770
534    5.720289
566    0.679511
852   -2.782775
Name: Strength, dtype: float64

In [24]:
#third weak learner
tree_reg3 = DecisionTreeRegressor(max_depth = 4)
tree_reg3.fit(X_train, y3)

DecisionTreeRegressor(max_depth=4)

In [25]:
y4 = y3 - tree_reg3.predict(X_train)
y4[:5]

886    4.917120
249   -1.944669
534    1.406214
566   -3.634565
852    1.608569
Name: Strength, dtype: float64

In [26]:
# let's calculate the final score (we can obviously increase the number of weak learners if we want)
y_pred = sum(tree.predict(X_test) for tree in (tree_reg1, tree_reg2, tree_reg3))

In [27]:
from sklearn.metrics import r2_score

In [28]:
r2_score(y_test, y_pred)

0.7354613528619516

# Otomatik Gradient Boosting

In [29]:
from sklearn.ensemble import GradientBoostingRegressor

In [30]:
gbr = GradientBoostingRegressor()

In [31]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor()

In [32]:
y_pred = gbr.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(r2)

0.8408648100445971

In [33]:
params = {
    'loss' : ['squared_error', 'absolute_error', 'huber', 'quantile'],
    'learning_rate' : [0.01, 0.1, 1],
    'n_estimators' : [1, 10, 50, 100, 200, 500],
    'criterion' : ['friedman_mse', 'squared_error']
}

In [34]:
from sklearn.model_selection import RandomizedSearchCV

In [35]:
import warnings
warnings.filterwarnings('ignore')
rscv = RandomizedSearchCV(estimator=GradientBoostingRegressor(), param_distributions=params, verbose=3, refit=True)

In [36]:
rscv.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=squared_error, learning_rate=0.1, loss=quantile, n_estimators=500;, score=0.782 total time=   0.9s
[CV 2/5] END criterion=squared_error, learning_rate=0.1, loss=quantile, n_estimators=500;, score=0.634 total time=   0.8s
[CV 3/5] END criterion=squared_error, learning_rate=0.1, loss=quantile, n_estimators=500;, score=0.751 total time=   0.8s
[CV 4/5] END criterion=squared_error, learning_rate=0.1, loss=quantile, n_estimators=500;, score=0.767 total time=   0.8s
[CV 5/5] END criterion=squared_error, learning_rate=0.1, loss=quantile, n_estimators=500;, score=0.755 total time=   0.9s
[CV 1/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=500;, score=0.587 total time=   0.8s
[CV 2/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=500;, score=0.614 total time=   0.7s
[CV 3/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=500;, score=0.479 total time=   0.8s
[CV 4/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=500;, score=0.551 total time=   0.8s
[CV 5/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=500;, score=0.562 total time=   0.9s
[CV 1/5] END criterion=friedman_mse, learning_rate=0.1, loss=huber, n_estimators=500;, score=0.920 total time=   1.3s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.1, loss=huber, n_estimators=500;, score=0.926 total time=   1.3s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.1, loss=huber, n_estimators=500;, score=0.937 total time=   1.2s
[CV 4/5] END criterion=friedman_mse, learning_rate=0.1, loss=huber, n_estimators=500;, score=0.892 total time=   1.2s
[CV 5/5] END criterion=friedman_mse, learning_rate=0.1, loss=huber, n_estimators=500;, score=0.949 total time=   1.2s
[CV 1/5] END criterion=friedman_mse, learning_rate=1, loss=huber, n_estimators=500;, score=0.878 total time=   1.2s
[CV 2/5] END criterion=friedman_mse, learning_rate=1, loss=huber, n_estimators=500;, score=0.835 total time=   1.2s
[CV 3/5] END criterion=friedman_mse, learning_rate=1, loss=huber, n_estimators=500;, score=0.883 total time=   1.2s
[CV 4/5] END criterion=friedman_mse, learning_rate=1, loss=huber, n_estimators=500;, score=0.891 total time=   1.2s
[CV 5/5] END criterion=friedman_mse, learning_rate=1, loss=huber, n_estimators=500;, score=0.908 total time=   1.2s
[CV 1/5] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, n_estimators=100;, score=0.901 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, n_estimators=100;, score=0.894 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, n_estimators=100;, score=0.918 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, n_estimators=100;, score=0.869 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, n_estimators=100;, score=0.920 total time=   0.0s
[CV 1/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=500;, score=0.862 total time=   1.0s
[CV 2/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=500;, score=0.851 total time=   1.1s
[CV 3/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=500;, score=0.832 total time=   1.1s
[CV 4/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=500;, score=0.799 total time=   1.0s
[CV 5/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=500;, score=0.868 total time=   1.1s
[CV 1/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=200;, score=0.544 total time=   0.3s
[CV 2/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=200;, score=0.564 total time=   0.2s
[CV 3/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=200;, score=0.527 total time=   0.3s
[CV 4/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=200;, score=0.386 total time=   0.2s
[CV 5/5] END criterion=squared_error, learning_rate=1, loss=quantile, n_estimators=200;, score=0.600 total time=   0.3s
[CV 1/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=100;, score=0.596 total time=   0.1s
[CV 2/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=100;, score=0.604 total time=   0.1s
[CV 3/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=100;, score=0.521 total time=   0.1s
[CV 4/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=100;, score=0.504 total time=   0.1s
[CV 5/5] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, n_estimators=100;, score=0.592 total time=   0.1s
[CV 1/5] END criterion=squared_error, learning_rate=0.1, loss=huber, n_estimators=100;, score=0.897 total time=   0.2s
[CV 2/5] END criterion=squared_error, learning_rate=0.1, loss=huber, n_estimators=100;, score=0.893 total time=   0.2s
[CV 3/5] END criterion=squared_error, learning_rate=0.1, loss=huber, n_estimators=100;, score=0.914 total time=   0.2s
[CV 4/5] END criterion=squared_error, learning_rate=0.1, loss=huber, n_estimators=100;, score=0.855 total time=   0.2s
[CV 5/5] END criterion=squared_error, learning_rate=0.1, loss=huber, n_estimators=100;, score=0.922 total time=   0.2s
[CV 1/5] END criterion=squared_error, learning_rate=0.01, loss=squared_error, n_estimators=10;, score=0.126 total time=   0.0s
[CV 2/5] END criterion=squared_error, learning_rate=0.01, loss=squared_error, n_estimators=10;, score=0.099 total time=   0.0s
[CV 3/5] END criterion=squared_error, learning_rate=0.01, loss=squared_error, n_estimators=10;, score=0.072 total time=   0.0s
[CV 4/5] END criterion=squared_error, learning_rate=0.01, loss=squared_error, n_estimators=10;, score=0.103 total time=   0.0s
[CV 5/5] END criterion=squared_error, learning_rate=0.01, loss=squared_error, n_estimators=10;, score=0.109 total time=   0.0s

RandomizedSearchCV(estimator=GradientBoostingRegressor(),
                   param_distributions={'criterion': ['friedman_mse',
                                                      'squared_error'],
                                        'learning_rate': [0.01, 0.1, 1],
                                        'loss': ['squared_error',
                                                 'absolute_error', 'huber',
                                                 'quantile'],
                                        'n_estimators': [1, 10, 50, 100, 200,
                                                         500]},
                   verbose=3)

In [37]:
rscv.best_params_

{'n_estimators': 500,
 'loss': 'huber',
 'learning_rate': 0.1,
 'criterion': 'friedman_mse'}

In [38]:
gradient = GradientBoostingRegressor(n_estimators=500, loss='huber', learning_rate=0.1, criterion='friedman_mse')
gradient.fit(X_train, y_train)

GradientBoostingRegressor(loss='huber', n_estimators=500)

In [39]:
y_pred = gradient.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(r2)

0.8615161893249806